services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: no
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html  # ホストマシンのディレクトリをマウント
    platform: linux/amd64  # 追加

  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: no
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db_data:/var/lib/mysql  # ホストマシンのディレクトリをマウント
    ports:
      - "3306:3306"
    platform: linux/amd64  # 追加

volumes:
  wordpress_data:
  db_data:
